theme: jekyll-theme-time-machine
title: Welcome to Marco Morley Project Pages!
Description: Please look around.  My only disclaimer; I am not a professional! I am learning and have
also learned that I am not that good.  Be patient! Be respectful and help me not only help myself but 
others that are here to learn.
